/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.*;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author timjl
 */
public class MapPanel extends javax.swing.JPanel {

    private boolean showUnitsMode = true;
    private boolean testMode = false;
    private Game game;
    /**
     * Creates new form mapPanel
     */
    public MapPanel() {
        initComponents();
        
        
    }

    public void setGame (Game g) {
        game = g;
        this.repaint();
    }
    
    @Override
    public void paintComponent (Graphics g) {
        super.paintComponent(g);
        
        Image img = null;
        

        
        try {
            img = ImageIO.read(getClass().getResource("/GUI/map_c.gif"));
            if (img != null){
                g.drawImage(img, 0, 0, null);

                if (game != null){
                    
                    for (Map.Entry m : game.getAllUnits().entrySet()) {

                        Unit u = (Unit)m.getValue();
                        Border b = u.getPosition();
                        Player p = game.getAllPlayers().get(u.getOwnerId());
                        
                        //For a black outline.
                        //g.setFont(new Font("serif", Font.BOLD, 20));
                        //g.setColor(java.awt.Color.BLACK);
                        //g.drawString(unit, x-1, y-1);

                        g.setFont(new Font("serif", Font.BOLD, 15));

                        String colour = p.getColour();
                        switch (colour) {
                            case "BROWN":
                                g.setColor(new java.awt.Color(102, 51, 0));
                            break;

                            case "PINK":
                                g.setColor(new java.awt.Color(255, 102, 102));
                            break;

                            case "BLUE":
                                g.setColor(java.awt.Color.BLUE);
                            break;

                            case "BLACK":
                                g.setColor(java.awt.Color.BLACK);
                            break;

                            case "GREEN":
                                g.setColor(java.awt.Color.GREEN);
                            break;

                            case "PURPLE":
                                g.setColor(new java.awt.Color(102, 0, 153));
                            break;

                            case "YELLOW":
                                g.setColor(java.awt.Color.YELLOW);
                            break;

                            default:
                                g.setColor(java.awt.Color.BLACK);
                            break;

                        }

                        g.drawString(u.getTypeCode(), b.getMapX(), b.getMapY());
                    }

                }

            }
        } catch (IOException  ex) {
            Logger.getLogger(MapPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
